# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 菠菜眾長
subtitle: 李瑞豪的博客
description: 从ACM到Web，分享程序、技巧、干货，记录心情、学习、成长！ #网站描述seo
keywords: 李瑞豪,李瑞豪的博客,菠菜眾長,博採眾長,Cell,lruihao,李四啊_,hexo个人博客,RUI豪小栈
author: 李瑞豪
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://lruihao.cn
root: /
permalink: posts/:title.html #:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date
archive_generator:
  per_page: 10
  
# Category & Tag
default_category:
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: cos
  bucket: blog-
  appId: 
  secretId: 
  secretKey: 
  region: ap-chengdu
- type: git
  repository:
    github: git@github.com:Lruihao/Lruihao.github.io.git,master
    #coding: git@git.coding.net:liruihao/liruihao.git,master
  message: "《菠菜眾長》日常更新: {{ now('YYYY-MM-DD HH:mm:ss') }}"
- type: baidu_url_submitter

# Security
##
encrypt:
  enable: true

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false

lazyload:
  enable: true
  onlypost: true
  loadingImg: /images/loading_img.gif # eg /images/loading.gif

baidu_url_submit:
  count: 300 ## 提交最新的链接
  host: lruihao.cn ## 在百度站长平台中注册的域名
  token: RnnAQZVlFN31cs7j  ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

nofollow:
    enable: true
    exclude:
    - lruihao.cn
    - www.lruihao.cn
    - lruihao.github.io
    - player.lruihao.cn
    - ziyuan.lruihao.cn
    - pan.lruihao.cn

# 代码压缩
all_minifier: true

html_minifier:
  enable: true
  ignore_error: false
  exclude:
    - 'lib/pdf/web/viewer.html'
  
css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  #output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier: 
  enable: false # 图片不压缩
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# hexo-pwa
# use "npm install --save hexo-pwa"
# pwa:
#   manifest:
#     path: /manifest.json
#     body:
#       name: 博採眾長 — LRH's blog
#       short_name: 博採眾長
#       icons:
#         - src: /images/icons/36.png
#           sizes: 36x36
#           type: image/png
#         - src: /images/icons/48.png
#           sizes: 48x48
#           type: image/png
#         - src: /images/icons/72.png
#           sizes: 72x72
#           type: image/png
#         - src: /images/icons/96x96.png
#           sizes: 96x96
#           type: image/png
#         - src: /images/icons/144.png
#           sizes: 144x144
#           type: image/png
#         - src: /images/icons/192.png
#           sizes: 192x192
#           type: image/png
#         - src: /images/icons/512.png
#           sizes: 512x512
#           type: image/png
#       start_url: /index.html
#       theme_color: '#ffffff'
#       background_color: '#ffffff'
#       display: standalone
#   serviceWorker:
#     path: /sw.js
#     preload:
#       urls:
#         - /
#       posts: 5
#     opts:
#       networkTimeoutSeconds: 5
#     routes:
#       - pattern: !!js/regexp /hm.baidu.com/
#         strategy: networkOnly
#       - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
#         strategy: cacheFirst
#       - pattern: !!js/regexp /\//
#         strategy: networkFirst
#   priority: 5
